# Generated by Django 4.2.4 on 2023-09-26 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0002_remove_cartitem_cart_cartitem_cart_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Net_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='net_amount',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cart.net_amount'),
            preserve_default=False,
        ),
    ]
