# Generated by Django 4.2.4 on 2023-09-26 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_product_offer_percentage'),
        ('cart', '0003_net_amount_cartitem_net_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='net_amount',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.product'),
            preserve_default=False,
        ),
    ]
