# Generated by Django 4.2.4 on 2023-09-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_address_landmark_alter_address_address_line_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
    ]
