# Generated by Django 4.2.4 on 2023-09-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orders_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_type',
            field=models.CharField(max_length=100),
        ),
    ]
